"""add item table

Revision ID: 9e451ccd8974
Revises: 91979b40eb38
Create Date: 2022-09-14 15:10:00.672229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9e451ccd8974"
down_revision = "91979b40eb38"
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        "items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("price", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_items_id"), "items", ["id"], unique=False)
    op.create_index(op.f("ix_items_name"), "items", ["name"], unique=True)

    op.alter_column(
        "user", "is_active", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "user", "is_superuser", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    op.drop_column("user", "address")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "address",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.alter_column(
        "user", "is_superuser", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "user", "is_active", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.drop_index(op.f("ix_items_name"), table_name="items")
    op.drop_index(op.f("ix_items_id"), table_name="items")
    op.drop_table("items")
    # ### end Alembic commands ###
